# Generated by Django 2.1 on 2018-09-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Some default subtitle', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default_post_image.jpg', upload_to='post_pics'),
        ),
    ]
